// Module2_FrontendDev IniyanRam/handson_08 vue/student-portal-vue/src/components/Header.vue
<template>
  <header class="header">
    <h1>Student Portal</h1>

    <p>
      Enrolled Courses :
      {{ store.enrolledCourses.length }}
    </p>
  </header>
</template>

<script setup>
import { useEnrollmentStore } from '../stores/enrollment'

const store = useEnrollmentStore()
</script>

<style scoped>
.header {
  background-color: #4caf50;
  color: white;
  padding: 15px;
  text-align: center;
}
</style>

// Module2_FrontendDev IniyanRam/handson_05_and_06_react/student-portal-react/src/components/Header.jsx
import { Link } from "react-router-dom";
import { useSelector } from "react-redux";

function Header() {

  const enrolledCourses =
    useSelector(
      state => state.enrollment.enrolledCourses
    );

  return (

    <header>

      <h1>Student Portal</h1>

      <nav>
        <Link to="/">Home</Link>{" | "}
        <Link to="/courses">Courses</Link>{" | "}
        <Link to="/profile">Profile</Link>
      </nav>

      <p>
        Enrolled Courses :
        {enrolledCourses.length}
      </p>

      <hr />

    </header>

  );

}

export default Header;
