// Module2_FrontendDev IniyanRam/handson_05/student-portal-react/src/components/CourseCard.jsx
function CourseCard(props) {
  return (
    <div className="course-card">
      <h2>{props.name}</h2>

      <p><strong>Code:</strong> {props.code}</p>

      <p><strong>Credits:</strong> {props.credits}</p>

      <p><strong>Grade:</strong> {props.grade}</p>

      <button onClick={() => props.onEnroll(props.course)}>
        Enroll
      </button>
    </div>
  );
}

export default CourseCard;

// Module2_FrontendDev IniyanRam/handson_08 vue/student-portal-vue/src/components/CourseCard.vue
<template>
  <div class="card">
    <h3>{{ name }}</h3>
    <p><strong>Code:</strong> {{ code }}</p>
    <p><strong>Credits:</strong> {{ credits }}</p>
    <p><strong>Grade:</strong> {{ grade }}</p>
  </div>
</template>

<script setup>
defineProps({
  name: String,
  code: String,
  credits: Number,
  grade: String,
})
</script>

<style scoped>
.card {
  border: 1px solid #ccc;
  border-radius: 8px;
  padding: 15px;
  margin: 10px;
}
</style>
